//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj.
        /// </summary>
        public static string broj {
            get {
                return ResourceManager.GetString("broj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastavi.
        /// </summary>
        public static string continue1 {
            get {
                return ResourceManager.GetString("continue1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hrvatski.
        /// </summary>
        public static string croatian {
            get {
                return ResourceManager.GetString("croatian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engleski.
        /// </summary>
        public static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omiljeni tim:.
        /// </summary>
        public static string favouriteTeam {
            get {
                return ResourceManager.GetString("favouriteTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ženski.
        /// </summary>
        public static string female {
            get {
                return ResourceManager.GetString("female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIFA Code.
        /// </summary>
        public static string fifaCode {
            get {
                return ResourceManager.GetString("fifaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cijeli Zaslon.
        /// </summary>
        public static string fullScreen {
            get {
                return ResourceManager.GetString("fullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Golovi.
        /// </summary>
        public static string goals {
            get {
                return ResourceManager.GetString("goals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        public static string ime {
            get {
                return ResourceManager.GetString("ime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info Domaci.
        /// </summary>
        public static string infoDomaci {
            get {
                return ResourceManager.GetString("infoDomaci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info gosti.
        /// </summary>
        public static string infoGosti {
            get {
                return ResourceManager.GetString("infoGosti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info Igrac.
        /// </summary>
        public static string infoIgrac {
            get {
                return ResourceManager.GetString("infoIgrac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info tim.
        /// </summary>
        public static string infoTim {
            get {
                return ResourceManager.GetString("infoTim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeste li sigurni?.
        /// </summary>
        public static string jesteLiSigurni {
            get {
                return ResourceManager.GetString("jesteLiSigurni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapetan .
        /// </summary>
        public static string kapetan {
            get {
                return ResourceManager.GetString("kapetan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velika.
        /// </summary>
        public static string large {
            get {
                return ResourceManager.GetString("large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muški.
        /// </summary>
        public static string male {
            get {
                return ResourceManager.GetString("male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Srednja.
        /// </summary>
        public static string medium {
            get {
                return ResourceManager.GetString("medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nerješeno.
        /// </summary>
        public static string neRjeseno {
            get {
                return ResourceManager.GetString("neRjeseno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne.
        /// </summary>
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nogometni teren.
        /// </summary>
        public static string nogometniTerenTitle {
            get {
                return ResourceManager.GetString("nogometniTerenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odigrane utakmice.
        /// </summary>
        public static string odigraneUtakmice {
            get {
                return ResourceManager.GetString("odigraneUtakmice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protivnik:.
        /// </summary>
        public static string oposingTeam {
            get {
                return ResourceManager.GetString("oposingTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original.
        /// </summary>
        public static string original {
            get {
                return ResourceManager.GetString("original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobjede.
        /// </summary>
        public static string pobjede {
            get {
                return ResourceManager.GetString("pobjede", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porazi.
        /// </summary>
        public static string porazi {
            get {
                return ResourceManager.GetString("porazi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postavke.
        /// </summary>
        public static string postavke {
            get {
                return ResourceManager.GetString("postavke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozicija.
        /// </summary>
        public static string pozicija {
            get {
                return ResourceManager.GetString("pozicija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primljeni golovi.
        /// </summary>
        public static string primljeniGolovi {
            get {
                return ResourceManager.GetString("primljeniGolovi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razlika.
        /// </summary>
        public static string razlika {
            get {
                return ResourceManager.GetString("razlika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite sve postavke.
        /// </summary>
        public static string selectAllSettings {
            get {
                return ResourceManager.GetString("selectAllSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite spol.
        /// </summary>
        public static string selectGender {
            get {
                return ResourceManager.GetString("selectGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite jezik.
        /// </summary>
        public static string selectLanguage {
            get {
                return ResourceManager.GetString("selectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite veličinu ekrana.
        /// </summary>
        public static string selectScreenSize {
            get {
                return ResourceManager.GetString("selectScreenSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postavke.
        /// </summary>
        public static string settingsWindowTitle {
            get {
                return ResourceManager.GetString("settingsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slika.
        /// </summary>
        public static string slika {
            get {
                return ResourceManager.GetString("slika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mala.
        /// </summary>
        public static string small {
            get {
                return ResourceManager.GetString("small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timovi.
        /// </summary>
        public static string teamsWindowTitle {
            get {
                return ResourceManager.GetString("teamsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da.
        /// </summary>
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj zabijenih golova.
        /// </summary>
        public static string zabijeniGolovi {
            get {
                return ResourceManager.GetString("zabijeniGolovi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zabijeni golovi.
        /// </summary>
        public static string zabijeniGolovi1 {
            get {
                return ResourceManager.GetString("zabijeniGolovi1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zemlja.
        /// </summary>
        public static string zemlja {
            get {
                return ResourceManager.GetString("zemlja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Žuti kartoni.
        /// </summary>
        public static string zutikartoni {
            get {
                return ResourceManager.GetString("zutikartoni", resourceCulture);
            }
        }
    }
}
